[package]
name = "the_modern_cpp_challenge_in_rust"
version = "0.1.0"
authors = ["ASzwarc <szwarc.adam@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
